=== Some general tips
Before you start fully developing with Quarkus, I would strongly advice you to have a look at the official link:https://quarkus.io/guides/[Starter Guides] (use filter Starter Guides). These will introduce you to more of the core concepts and you will become familiar with Quarkus's ins and outs. Also look at the link:https://quarkus.io/guides/cdi#can-i-use-setter-and-constructor-injection[Dependency Injection Framework] provided, since it will greatly reduce confusion between when to use @ApplicationScoped / @Singleton, Qualifiers, etc.

=== Dev UI Tips
The Dev UI can help with debugging and configuring a lot. You can use the link:http://localhost:8080/q/dev/io.quarkus.quarkus-vertx-http/config[Config Editor] while the application is running to configure basically everything you would normally write by hand in the application.properties or other configuration files, while being able to search and filter them. You can also have a look for example at the link:http://localhost:8080/q/dev/io.quarkus.quarkus-hibernate-orm/persistence-units[generated hibernate create and delete scripts] for your database for easier DB-debugging. 

=== Careful Deployment
Be carfeul while making your application production ready, especially when you are using Dev Services. These services are quick to use, but before deployment, you will have to adapt you application to work with real databases, kubernetes, etc. Quarkus provides guides on how to transition to production-ready code. For example like link:https://quarkus.io/guides/deploying-to-kubernetes[this] one for Kubernetes.

=== Cheat-Sheet
Lastly, there is a link:https://lordofthejars.github.io/quarkus-cheat-sheet/[Quarkus Cheat-Sheet] that should covers everything one should need when developing Quarkus application. It also provides links to further resources, if one would have to dive deeper into any topic. I would strongly recommend having it open while developing, regardless of how familiar you already are with Quarkus.