=== Why it was created
Java frameworks have traditionally been designed for monolithic applications with long start-up times and high memory requirements. Quarkus is a Java framework designed with the need for cloud-native applications in mind. With the rise of cloud computing, containers, and Kubernetes, there is a growing demand for applications that are optimized for these environments. Quarkus aims to address this demand by providing developers with a framework for building cloud applications with ease. Its ultimate goal is to make Java a leading platform in Kubernetes and serverless environments by delivering packages that are small in size, have a low memory footprint, and offer fast start-up times. In addition to these performance benefits, Quarkus also supports a wide range of distributed application architectures, giving developers the flexibility to build applications that meet the specific needs of their organizations.

It is completely open-source and licensed under the link:https://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0], allowing everyone to have a look at the source code or even contribute in the development process. They provide an open community where new ideas can be shared, discussed and implemented to build the future of Java applications.

For performance data between Spring and Quarkus look link:https://www.baeldung.com/spring-boot-vs-quarkus[here].

=== The Core Concepts
==== Developer Joy
It includes tools and features such as live code reload and extensive documentation to facilitate a smooth development experience, and it provides a full stack framework, using only "Best of Breed Libraries and Standards" as it is described on their website, that are used to help developers transition from other frameworks and improve their quality of life while coding. 

==== Kubernetes-native
Quarkus is designed to be easily scalable and optimized for cloud applications, and it was built to work seamlessly with Kubernetes. It includes features such as containerization, which allows applications to be easily deployed in Kubernetes clusters, and automatic generation of configuration and container files, eliminating the need for manual YAML file creation. Quarkus also has an extension that allows application configurations to be managed using Kubernetes ConfigMaps and Secrets, making it easy to share sensitive information such as passwords and API keys between services. Overall, Quarkus simplifies the process of deploying and managing applications in Kubernetes and Docker, enabling developers to take advantage of its capabilities without having to learn every intricate detail of the platform.

===== Tracing and Health
Through the use of link:https://opentracing.io/[OpenTracing], developers can implement tracing in their distributed microservices, which helps with debugging and tracking of the process state. 

Quarkus incorporates SmallRye Health, which is based on the MicroProfile Health specification, to enable applications to provide information about their status to external viewers in a Kubernetes environment. This information can be used by automated processes to decide whether to restart or discard the application.

==== Imperative / Reactive
Quarkus supports the imperative as well as the reactive programming paradigm. This means that it can be used for a plethora of different applications ranging from monolithic imperative to distributed reactive microservice-based applications. Imperative and reactive programming patterns and components can also be mixed and matched in the same project, allowing developers to quickly adapt to their requirements. 